[[bond]]
source = "tpknam1qzfsajsektqcz33f07fcsd7fkn5a8fzk9rdz7gh4wegrv58svrq2cssm7l4"
validator = "tnam1q8xasrt0q8qrkqj5s9r9xw3ee0gx5mqwyukhe699"
amount = "3000"

[bond.signatures]
tpknam1qzfsajsektqcz33f07fcsd7fkn5a8fzk9rdz7gh4wegrv58svrq2cssm7l4 = "signam1qqkgdvrk0tj8le3ye9n7vz622wuvxw0p8ljad49kal48wf6fxljx9stv9pqayfjyqqvdhytmmh2fm8ucr438ye5d4vcksa9gawdqnnc0jcp4ve"

