[[bond]]
source = "tpknam1qpqkuf568lqccx6szaqv3tnmt5v07zh3xvykfrpztyqpem9zfj4qj2cqrt3"
validator = "tnam1qxzwta6uhcsv40a8l4g5t07q0ey50c9dlyt3s272"
amount = "23443.9"

[bond.signatures]
tpknam1qpqkuf568lqccx6szaqv3tnmt5v07zh3xvykfrpztyqpem9zfj4qj2cqrt3 = "signam1qzhjslcmpf42c2l8yayagz07r7dc9au8r0cusjdxkwwnkmtt9a204q0fkyxnep0hgvs0c8t7yhzds4zeruregrg5h7lxhs7vjaezl5sqkjk2sf"

