[[bond]]
source = "tpknam1qqekk84v2296kj5068zjss3r9e3n0tzc9nahxh7edt7wl95t2zrq2p8snhz"
validator = "tnam1qxsx2ezu89gx252kwwluqp7hadyp285tkczhaqg0"
amount = "3500"

[bond.signatures]
tpknam1qqekk84v2296kj5068zjss3r9e3n0tzc9nahxh7edt7wl95t2zrq2p8snhz = "signam1qrsvc85g4a4xuhvce5r0hl6kvwehxtya26ekgju7d0mxfrfjflj6njw387npfgl3wp95mfa6kmne0sk38qqgecqa0r28gpvnuxz0jvg8g5e4ee"

