[[bond]]
source = "tpknam1qz5wa6hsmm58z3nw9ednqwefae2yt9mjqkah8c3vxsgfv4d3hg6mgdzl2ud"
validator = "tnam1q8wldcr49mhm92a69fmf847d8rn48e6gcql2s4ya"
amount = "10"

[bond.signatures]
tpknam1qz5wa6hsmm58z3nw9ednqwefae2yt9mjqkah8c3vxsgfv4d3hg6mgdzl2ud = "signam1qr3mssk4vc458509tpe7f09etujc8qvl6lw7cvpqq3utra9azjsjxynx7fc4pvspkql9682y5kkschmra4qnrpe8exz3mv8awz58jcc8q8w82m"

