[[bond]]
source = "tpknam1qpmyqv2pjscdh4v47arwj0e96s9rjjyc2wcq4avwv0tskqjkaachjwnmalz"
validator = "tnam1qxq08djyzzrhgchwv2datwhk3cghtseg953ruh2y"
amount = "400"

[bond.signatures]
tpknam1qpmyqv2pjscdh4v47arwj0e96s9rjjyc2wcq4avwv0tskqjkaachjwnmalz = "signam1qqenlegk85035lgnh2c5dvq6nmsmg92ck8rytary89ucqwht4787n8m78upe0w7lam2w6nzmpk0kcaqt77gycv70cr99e9cjv7vpncq0jf2vg9"

