[[bond]]
source = "tpknam1qqkyssfmavnrwk0qnk6skjmm5pmrqrdqnrkvnevevvrt462f0yk7qu4n3yl"
validator = "tnam1qyd33xrjdpr3hwhy0ckut7lk56gd5gjflgtul8hs"
amount = "50"

[bond.signatures]
tpknam1qqkyssfmavnrwk0qnk6skjmm5pmrqrdqnrkvnevevvrt462f0yk7qu4n3yl = "signam1qz7p7tkseuphgwlqkfy5zxlc4jk5sm22vtqrf66y67dt55yn6p2x0myllwkuyk5scj88rrld38nmv64qp0x6un6zyqhh2z8zejgtw3cqz97sne"

