[[bond]]
source = "tpknam1qqf55glhn9puwlqexkc38tg3pe5jj7c346dn5kvwa675fyv5x7a22f6wvpl"
validator = "tnam1q9pt4hukg0ga362jq2slhg4tuf692zqqngzzz54k"
amount = "100"

[bond.signatures]
tpknam1qqf55glhn9puwlqexkc38tg3pe5jj7c346dn5kvwa675fyv5x7a22f6wvpl = "signam1qpp0zhq895qju9k3ate42z9txduhhm9jvc47lqjy53qrf9xnm3kcul5edgrul5kvp4axu7smvy3elech28m2czv96g9tu5sdvjhwe0gg8uatud"

