[[bond]]
source = "tpknam1qrgfgldxag9hqzkc7rfqlc2g7kel8nelyh7qlc6a6hvcqa8860ntshjz7v5"
validator = "tnam1q8lhvxys53dlc8wzlg7dyqf9avd0vff6wvav4amt"
amount = "1000000"

[bond.signatures]
tpknam1qrgfgldxag9hqzkc7rfqlc2g7kel8nelyh7qlc6a6hvcqa8860ntshjz7v5 = "signam1qrjvc5f3t3jmgevph5nkhmz77a9ceu07j35plc38vs3vr5ksf6nrjkkunzentmu4kfjukaz562fufp3kvvemn0lmaq0hz5lsrh368fgr0p0vtn"

