[[bond]]
source = "tpknam1qqw6awvekhtxhw7v53ku7r48c5mu6n0jnj9g4uhdrzm5yymefd0c2xsku4k"
validator = "tnam1q8lhvxys53dlc8wzlg7dyqf9avd0vff6wvav4amt"
amount = "114.78"

[bond.signatures]
tpknam1qqw6awvekhtxhw7v53ku7r48c5mu6n0jnj9g4uhdrzm5yymefd0c2xsku4k = "signam1qze7qrc6xv99qxwf9rl78gu7gvnl08vk0yw99yvmtha3sr2mujphxk48srfdfwmm8xt89q88l7a07dvwkvd9r3ly53zxdrvftmuq0lqqs00c0h"

