[[bond]]
source = "tpknam1qqdvk4cvqev2muqm7gdyxdv90q0ajp0udevdsungdwd4wctzs2g0k3wcufj"
validator = "tnam1q8dtazgc7y9xx00lq4d2pnacvtz29p5mvcxwat74"
amount = "4360"

[bond.signatures]
tpknam1qqdvk4cvqev2muqm7gdyxdv90q0ajp0udevdsungdwd4wctzs2g0k3wcufj = "signam1qq8wl46nfqdvchnngd37mfvr7uelk83ed6fhnepefhlhg83tcva2wrknyftz63axgwmkd9eef5xyrzl4q9yqxp6psk952y8v9wlmszc0vt8ym4"

