[[bond]]
source = "tpknam1qqw6awvekhtxhw7v53ku7r48c5mu6n0jnj9g4uhdrzm5yymefd0c2xsku4k"
validator = "tnam1q8lhvxys53dlc8wzlg7dyqf9avd0vff6wvav4amt"
amount = "114.78"

[bond.signatures]
tpknam1qqw6awvekhtxhw7v53ku7r48c5mu6n0jnj9g4uhdrzm5yymefd0c2xsku4k = "signam1qze7qrc6xv99qxwf9rl78gu7gvnl08vk0yw99yvmtha3sr2mujphxk48srfdfwmm8xt89q88l7a07dvwkvd9r3ly53zxdrvftmuq0lqqs00c0h"

[[bond]]
source = "tpknam1qrgfgldxag9hqzkc7rfqlc2g7kel8nelyh7qlc6a6hvcqa8860ntshjz7v5"
validator = "tnam1q8lhvxys53dlc8wzlg7dyqf9avd0vff6wvav4amt"
amount = "1000000"

[bond.signatures]
tpknam1qrgfgldxag9hqzkc7rfqlc2g7kel8nelyh7qlc6a6hvcqa8860ntshjz7v5 = "signam1qrjvc5f3t3jmgevph5nkhmz77a9ceu07j35plc38vs3vr5ksf6nrjkkunzentmu4kfjukaz562fufp3kvvemn0lmaq0hz5lsrh368fgr0p0vtn"

[[bond]]
source = "tpknam1qpshppnclu7cs4g25wv99gjyzu7ng4rmwrrc686xawa2emp657arcfupn8v"
validator = "tnam1qydvhqdu2q2vrgvju2ngpt6yhrehu525pus6m28p"
amount = "78"

[bond.signatures]
tpknam1qpshppnclu7cs4g25wv99gjyzu7ng4rmwrrc686xawa2emp657arcfupn8v = "signam1qrmtv7zj9qzajcehuhkpmhpgy3ayttxd22jz93x9h7x433k6f76pj94hqwnkwm7y645dmruzhdr9k7ymqsde234x7cdgeaggzuhnfuc9z5970q"

[[bond]]
source = "tpknam1qrjejl4lhn507xtzjhkd4p6hysmdvdgrrz9llyvnpd90zrnus7sqw07sntn"
validator = "tnam1qxzwta6uhcsv40a8l4g5t07q0ey50c9dlyt3s272"
amount = "35"

[bond.signatures]
tpknam1qrjejl4lhn507xtzjhkd4p6hysmdvdgrrz9llyvnpd90zrnus7sqw07sntn = "signam1qpry2duyq39rzzplu3vj2dp7vzylpzd435g59py3xkuxunurzkkxcg0m8j3csj6fxs7uvuynd5j4dma5n0xd295w74lnhp4r9nk0d3g0raxn96"

[[bond]]
source = "tpknam1qrjejl4lhn507xtzjhkd4p6hysmdvdgrrz9llyvnpd90zrnus7sqw07sntn"
validator = "tnam1q8lhvxys53dlc8wzlg7dyqf9avd0vff6wvav4amt"
amount = "8"

[bond.signatures]
tpknam1qrjejl4lhn507xtzjhkd4p6hysmdvdgrrz9llyvnpd90zrnus7sqw07sntn = "signam1qp2ffu69p60x0035hl3jgfzauxer5rgvkc9lkkm8n57mvhh7pznpj4evc4jjk3nkjlng7etjhm9zg7u4sfxskxnhszufmh7mujzj0nc9vdefye"

[[bond]]
source = "tpknam1qrjejl4lhn507xtzjhkd4p6hysmdvdgrrz9llyvnpd90zrnus7sqw07sntn"
validator = "tnam1q8lhvxys53dlc8wzlg7dyqf9avd0vff6wvav4amt"
amount = "8.48"

[bond.signatures]
tpknam1qrjejl4lhn507xtzjhkd4p6hysmdvdgrrz9llyvnpd90zrnus7sqw07sntn = "signam1qq7yn9e0jwwtmavqqp2utye3qzxnz4jx2tyfy3wxv5fvzl73jr5vcdarvnejre0cdynhefm8m8n7ajy570m7mqckkukkjcwdprzuv0s92jfswk"

[[bond]]
source = "tpknam1qpqkuf568lqccx6szaqv3tnmt5v07zh3xvykfrpztyqpem9zfj4qj2cqrt3"
validator = "tnam1qxzwta6uhcsv40a8l4g5t07q0ey50c9dlyt3s272"
amount = "23443.9"

[bond.signatures]
tpknam1qpqkuf568lqccx6szaqv3tnmt5v07zh3xvykfrpztyqpem9zfj4qj2cqrt3 = "signam1qzhjslcmpf42c2l8yayagz07r7dc9au8r0cusjdxkwwnkmtt9a204q0fkyxnep0hgvs0c8t7yhzds4zeruregrg5h7lxhs7vjaezl5sqkjk2sf"

[[bond]]
source = "tpknam1qqekk84v2296kj5068zjss3r9e3n0tzc9nahxh7edt7wl95t2zrq2p8snhz"
validator = "tnam1qxsx2ezu89gx252kwwluqp7hadyp285tkczhaqg0"
amount = "3500"

[bond.signatures]
tpknam1qqekk84v2296kj5068zjss3r9e3n0tzc9nahxh7edt7wl95t2zrq2p8snhz = "signam1qrsvc85g4a4xuhvce5r0hl6kvwehxtya26ekgju7d0mxfrfjflj6njw387npfgl3wp95mfa6kmne0sk38qqgecqa0r28gpvnuxz0jvg8g5e4ee"

[[bond]]
source = "tpknam1qpmyqv2pjscdh4v47arwj0e96s9rjjyc2wcq4avwv0tskqjkaachjwnmalz"
validator = "tnam1qxq08djyzzrhgchwv2datwhk3cghtseg953ruh2y"
amount = "400"

[bond.signatures]
tpknam1qpmyqv2pjscdh4v47arwj0e96s9rjjyc2wcq4avwv0tskqjkaachjwnmalz = "signam1qqenlegk85035lgnh2c5dvq6nmsmg92ck8rytary89ucqwht4787n8m78upe0w7lam2w6nzmpk0kcaqt77gycv70cr99e9cjv7vpncq0jf2vg9"

[[bond]]
source = "tpknam1qpwrrdm7448hn2d0a5ut4fk3nf4r3294d8ejarsyuzg2te93fv8zshk8aaw"
validator = "tnam1qygz4sn400y9g90rt5jx6ja0wrcx3y7u0c0ue6dq"
amount = "106.88"

[bond.signatures]
tpknam1qpwrrdm7448hn2d0a5ut4fk3nf4r3294d8ejarsyuzg2te93fv8zshk8aaw = "signam1qqkxnd00erqmv06hkcvv59dg95tcr4cnr3a0qqkh9wm0cumrwp8mupt7l49dwxcltwhf07uuen5es3gjg77n5sl3kpkrsmlnlm2xcuqgd8h266"

[[bond]]
source = "tpknam1qzfsajsektqcz33f07fcsd7fkn5a8fzk9rdz7gh4wegrv58svrq2cssm7l4"
validator = "tnam1q8xasrt0q8qrkqj5s9r9xw3ee0gx5mqwyukhe699"
amount = "3000"

[bond.signatures]
tpknam1qzfsajsektqcz33f07fcsd7fkn5a8fzk9rdz7gh4wegrv58svrq2cssm7l4 = "signam1qqkgdvrk0tj8le3ye9n7vz622wuvxw0p8ljad49kal48wf6fxljx9stv9pqayfjyqqvdhytmmh2fm8ucr438ye5d4vcksa9gawdqnnc0jcp4ve"

[[bond]]
source = "tpknam1qz5wa6hsmm58z3nw9ednqwefae2yt9mjqkah8c3vxsgfv4d3hg6mgdzl2ud"
validator = "tnam1q8wldcr49mhm92a69fmf847d8rn48e6gcql2s4ya"
amount = "10"

[bond.signatures]
tpknam1qz5wa6hsmm58z3nw9ednqwefae2yt9mjqkah8c3vxsgfv4d3hg6mgdzl2ud = "signam1qr3mssk4vc458509tpe7f09etujc8qvl6lw7cvpqq3utra9azjsjxynx7fc4pvspkql9682y5kkschmra4qnrpe8exz3mv8awz58jcc8q8w82m"

[[bond]]
source = "tpknam1qrpuwreqstgpn2zjdyjd52uva6glz2rlmpxgzmfmswngz7prfg4ucln352w"
validator = "tnam1qy7fms2m4kpx5khvp4x7r3pr8e4xdqghpsrsd0pn"
amount = "560"

[bond.signatures]
tpknam1qrpuwreqstgpn2zjdyjd52uva6glz2rlmpxgzmfmswngz7prfg4ucln352w = "signam1qr39tjh0t6az8ckddxkzya9jnkr3nv2wcu650764xzqrg4skgar885mu96309nkrfn2awumt90hdul98j6ey3kutnz6rzu82jtdqs6cvzxvac9"

[[bond]]
source = "tpknam1qrpuwreqstgpn2zjdyjd52uva6glz2rlmpxgzmfmswngz7prfg4ucln352w"
validator = "tnam1q8lhvxys53dlc8wzlg7dyqf9avd0vff6wvav4amt"
amount = "140"

[bond.signatures]
tpknam1qrpuwreqstgpn2zjdyjd52uva6glz2rlmpxgzmfmswngz7prfg4ucln352w = "signam1qzca40waynm2vu05ywdjh2qczk4qqtxt3veuqu7n47jf96l9mjy98mawjkzhsemt0ssc0gvsn4fhrv34kmfq8s8m7wj8za25p6025wcrtjvxwq"

[[bond]]
source = "tpknam1qpr6rngpuz26celqs48vhpte0fye2gjawszcgwrmfgxpkz8j4hmgkgzgmh9"
validator = "tnam1q8lhvxys53dlc8wzlg7dyqf9avd0vff6wvav4amt"
amount = "101.88"

[bond.signatures]
tpknam1qpr6rngpuz26celqs48vhpte0fye2gjawszcgwrmfgxpkz8j4hmgkgzgmh9 = "signam1qrj63q4ypancj0pw2x0mpuep24v8wf09mqz8tgpq5pcm532a6hfwgefj5y38049xy4k25ruuev0h9y2vuespzlcrm4jup25dvxusxqgthe4xvw"

[[bond]]
source = "tpknam1qrx4kadvfxu0qscp8fu8680t3hfejcvxnsyrrr8w2tl07cjdpn8ag22lrr7"
validator = "tnam1q87f9g34lagl5e6y482fwtad7870rk4vzsqaq7mf"
amount = "106"

[bond.signatures]
tpknam1qrx4kadvfxu0qscp8fu8680t3hfejcvxnsyrrr8w2tl07cjdpn8ag22lrr7 = "signam1qze6tj4lxeej275tpqu6y920h5qj8lyfn575u0phcu5g0tf462svqf00n8zgunkdrs6ukkxzsalf9emzp4l0xjzrr3jfap059xdlf8sd58jejy"

[[bond]]
source = "tpknam1qpqfwsv4x86mztdd79wvvj6s0s2uu5lwj03m7je3xwny9lmrs5qvkhhd5le"
validator = "tnam1qygz4sn400y9g90rt5jx6ja0wrcx3y7u0c0ue6dq"
amount = "106"

[bond.signatures]
tpknam1qpqfwsv4x86mztdd79wvvj6s0s2uu5lwj03m7je3xwny9lmrs5qvkhhd5le = "signam1qz2law35l5elkyc6sn2vl2u424h69tcgxzel6ycy2gtcfl220y5z7yvcdptu4p7hhf65yd30p2ysga9hkys76l9yyu3e889rmmgf9ug0zu90y2"
