name: Process Bond PRs into valid toml
on:
  pull_request:
    types:
      - opened
permissions:
  contents: write
jobs:
  process_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create clean branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'patch-${{ github.event.pull_request.number }}'
          sha: '6649294b1ab42131ffcdf643a7e1c985d29addf2'
      - name: Checkout clean branch first
        uses: actions/checkout@v4
        with:
          ref: 'patch-${{ github.event.pull_request.number }}'
      - name: Checkout the PR branch
        id: read-file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Process files changed in the current commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          changedFiles=$(git diff --name-only HEAD^)
          for file in $changedFiles; do
            echo "Processing file: $file"
            if [[ $file == *.toml ]]
            then
              content=`cat $file`
              echo content=$content >> $GITHUB_OUTPUT
              echo filename=$file >> $GITHUB_OUTPUT
            fi
          done
      - name: Output the changes on the clean branch
        run: |
          echo "Content: ${{ steps.read-file.outputs.content }}"
          echo "File: ${{ steps.read-file.outputs.filename }}"
