name: Process Bond PRs into valid toml
on:
  pull_request:
    types:
      - opened
permissions:
  contents: write
jobs:
  process_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (fetch last two commits) of the PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Checkout again for reasons
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Process files changed in the current commit
        run: |
          changedFiles=$(git diff --name-only HEAD^)
          for file in $changedFiles; do
            echo "Processing file: $file"
            if [[ $file == *.toml ]]
            then
              cat $file | base64 -d > valid-bond.toml;
              rm $file;
              cat valid-bond.toml > $file;
            fi
          done
      - name: Commit and Push Changes        
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add valid-bond.toml
          git commit -a -m "Parsed base64 into valid toml [skip ci]" || echo "No changes to commit"
          rm valid-bond.toml
          git commit -a -m "Cleaning up bond toml [skip ci]"
          git push
      - name: Create clean branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'patch-${{ github.event.pull_request.number }}'
          sha: '6649294b1ab42131ffcdf643a7e1c985d29addf2'
      - name: Checkout again for more reasons
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Commit changes to clean branch then upstream PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          changedFiles=$(git diff --name-only HEAD^)
          for file in $changedFiles; do
            echo "Processing file: $file"
            if [[ $file != valid-bond.toml ]]
            then
              git add $file
              git commit -a -m '${{ github.event.pull_request.title }}'
              git push
            fi
          done
      - name: Create Upstream Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.SERVICE_TOKEN }}
        run: |
          PR_EXISTS=$(gh pr list --repo anoma/namada-mainnet-genesis --head "${{ github.repository_owner }}:${{ github.event.pull_request.head.ref }}" --json number --jq '.[].number')
          if [ -z "$PR_EXISTS" ]; then
            gh pr create \
              --title "${{ github.event.pull_request.title }}" \
              --body "${{ github.event.pull_request.body }}" \
              --head "${{ github.repository_owner }}:${{ github.event.pull_request.head.ref }}" \
              --base main \
              --repo anoma/namada-mainnet-genesis
          else
            echo "PR already exists: $PR_EXISTS"
          fi
