name: Process Bond PRs into valid toml
on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - 'patch**'
permissions:
  contents: write
jobs:
  process_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout clean branch first
        uses: actions/checkout@v4
        with:
          ref: 'patch-upstream'
      - name: Checkout the PR branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Process files changed in the current commit
        id: read-file
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          changedFiles=$(git diff --name-only HEAD^)
          for file in $changedFiles; do
            echo "Processing file: $file"
            if [[ $file == *.toml ]]
            then
              content=`cat $file`;
              echo content=$content >> $GITHUB_OUTPUT;
              echo filename=$file >> $GITHUB_OUTPUT;
              decoded='echo $content | base64 -d';
              gh pr comment ${{ github.event.pull_request.number }} -b $decoded;
            fi
          done
      - name: Output the changes on the clean branch
        run: |
          git switch 'patch-upstream'
          echo ${{ steps.read-file.outputs.content }} | base64 -d >> ${{ steps.read-file.outputs.filename }}
          git add ${{ steps.read-file.outputs.filename }}
          git commit -a -m '${{ github.event.pull_request.title }}'
          git push
      # We append the decoded values to the output file if one already exists
      # The Merge workflow is triggered by this push
      # We aren't currently merging this PR as the content is base64 encoded
      # Multiple submissions will result in new PRs following on from this one
