name: Process Bond PRs into valid toml
on:
  pull_request:
    types:
      - opened
permissions:
  contents: write
jobs:
  process_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (fetch last two commits) of the PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Checkout again for reasons
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Process files changed in the current commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          changedFiles=$(git diff --name-only HEAD^)
          for file in $changedFiles; do
            echo "Processing file: $file"
            if [[ $file == *.toml ]]
            then
              cat $file | base64 -d > valid-bond.toml;
              rm $file;
              cat valid-bond.toml > $file;
              git add $file;
              rm valid-bond.toml;
            fi
          done
          git stash
          git checkout -B 'patch-${{ github.event.pull_request.number }}' 6649294b1ab42131ffcdf643a7e1c985d29addf2
          git stash apply
          git commit -a -m '${{ github.event.pull_request.title }}'
          git push
