name: Process Bond toml PR from Patch into Merge
on:
  workflow_dispatch:
  push:
    branches:
      - patch-upstream
permissions:
  contents: write
jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:

    - name: Checkout target repo
      uses: actions/checkout@v3
      with:
        ref:  merge-upstream

    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: merge-upstream
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: main
        upstream_sync_repo: anoma/namada-mainnet-genesis
        upstream_repo_access_token: ${{ secrets.SERVICE_TOKEN }}
      
    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New upstream commits were synced."
    
    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new upstream commits to sync."
      
    - name: Get files changed in this push event
      uses: actions/checkout@v4
      with:
        ref: patch-upstream
        fetch-depth: 2

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45

    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed >> appending to merge toml"
          cat $file >> transactions/validityops-clu-bond.toml
          git add transactions/validityops-clu-bond.toml
          git commit -m "Appended bond submission from $file into validityops-clu-bond.toml"
          git push
        done

    - name: Create PR from Patch to Merge
      uses: devops-infra/action-pull-request@v0.5.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: patch-upstream
        target_branch: merge-upstream
        body: "**Automated bond submission from validityops.com**"
